# Site settings
title:       Ne smaukyklai COVID-19 skiepijime!
email:       linas.valiukas@gmail.com
author:      Linas Valiukas
description: "Vakarais skiepykime visus norinčius, tam naudodami dienos metu likusią nepanaudotą vakciną!"
baseurl:     ""
url:         "https://antismaukykla.com"
lang:        "lt"

# Optional features
animated:             false
show_related_posts:   false

text:
  og_locale: 'lt_LT'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  style: compressed
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
  - generate_icons.sh
  - todo.txt
  - serve.sh
  - install.sh
  - update_toc.sh
  - LICENSE.txt

